spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: 729351
    hikari:
      max-lifetime: 500000
  mail:
    host: smtp.126.com
    username: hx19461212@126.com
    address: hx19461212@126.com
    password: CGXFLBLZWZSAUVFU
    default-encoding: utf-8
    protocol: smtp
    port: 25
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 数据库索引
    database: 0
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池的最大数据库连接数
        max-active: 20
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
#日志输出配置
logging:
  level:
    root: info
    com.mys: debug
  file:
    name: log/blog-dev.log

